#!/bin/bash

CODE_COVERAGE_REPORTS=()
while read -r -d ''; do
  CODE_COVERAGE_REPORTS+=("$REPLY")
done < <(find . -type f -regex ".*/build/outputs/$CODE_COVERAGE_PATH" -print0)

for CODE_COVERAGE_REPORT in "${CODE_COVERAGE_REPORTS[@]}"; do
  FILE_NAME_WITH_EXTENSION=$(basename "$CODE_COVERAGE_REPORT")
  FILE_NAME="${FILE_NAME_WITH_EXTENSION%.*}"
  FILE_EXTENSION="${FILE_NAME_WITH_EXTENSION##*.}"

  CODE_COVERAGE_FOLDER=${CODE_COVERAGE_REPORT%/*}
  RENAME_FILE_NAME_WITH_EXTENSION="${FILE_NAME}_$CIRCLE_NODE_INDEX.$FILE_EXTENSION"
  CODE_COVERAGE_FILE="$CODE_COVERAGE_FOLDER/$RENAME_FILE_NAME_WITH_EXTENSION"

  echo "Saving code coverage report: $CODE_COVERAGE_FILE"
  mv "$CODE_COVERAGE_REPORT" "$CODE_COVERAGE_FILE"
done