version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

executors:
  docker:
    docker:
      - image: circleci/circleci-cli:0.1.9

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          executor:
            name: docker
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: "RC006,RC009"
      - shellcheck/check:
          filters: *filters
          exclude: SC1090
      - orb-tools/continue:
          orb_name: android-ci
          pipeline_number: << pipeline.number >>
          vcs_type: github
          requires: [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          filters: *filters