version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

workflows:
  pack:
    jobs:
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: github
          orb_name: willian-gama/android-ci
          requires: [orb-tools/pack]
          filters: *filters
