version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

# Custom checkout. Ref.: https://support.circleci.com/hc/en-us/articles/115015659247-How-do-I-modify-the-checkout-step#:~:text=If%20you%20need%20to%20change,process%20to%20suit%20your%20needs.&text=Please%20remember%20to%20remove%20the,step%20to%20process%20the%20checkout.
# CIRCLE_REPOSITORY_URL is not available with GitHub App authentication. Ref.: https://circleci.com/docs/variables/#built-in-environment-variables
# trigger_parameters.github_app.repo_url is available in Pipeline values - https://circleci.com/docs/variables/#pipeline-values
checkout: &checkout
  - run:
      name: Checkout
      command: git clone -b "$CIRCLE_BRANCH" << pipeline.trigger_parameters.github_app.repo_url >> .

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          pre-steps:
            - *checkout
          checkout: false
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/continue:
          pre-steps:
            - *checkout
          checkout: false
          orb_name: android-ci
          pipeline_number: << pipeline.number >>
          vcs_type: github
          requires: [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          filters: *filters