version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
          exclude: "RC006,RC009"
      - shellcheck/check:
          filters: *filters
          exclude: SC1090
      - orb-tools/publish:
          context: orb-publishing
          orb_name: kitmanlabs/android-automation
          vcs_type: github
          pub_type: dev
          dev_tags: dev:$CIRCLE_SHA1, dev:$CIRCLE_BRANCH
          enable_pr_comment: false
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters
      - orb-tools/continue:
          orb_name: android-ci
          pipeline_number: << pipeline.number >>
          vcs_type: github
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters