version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.1.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  <orb-name>: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-test:
    docker:
      - image: cimg/base:2024.07
    working_directory: ~/src
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - android-ci/decode_keystore
      - android-ci/load_workspace
      - android-ci/persist_workspace
      - android-ci/restore_gradle_cache
      - android-ci/save_gradle_cache

  bump_orb_version:
    docker:
      - image: cimg/base:2024.07
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Bump orb version
          command: src/scripts/create_tag.sh

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - command-test:
          filters: *filters
      - bump_orb_version:
          requires:
            - command-test
          filters:
            branches:
              only: main
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          requires:
            - bump_orb_version
      - orb-tools/publish:
          context: orb-publishing
          orb_name: willian-gama/android-ci
          vcs_type: github
          pub_type: production
          enable_pr_comment: false
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack