description: Full configuration

usage:
  version: 2.1
  orbs:
    automation: willian-gama/android-ci@1.0.26
  workflows:
    build_and_test:
      jobs:
        - automation/setup
        - automation/unit_tests:
            build_variant: debug
            run_screenshot_tests: true
            requires:
              - automation/setup
        - automation/ui_tests:
            build_variant: debug
            requires:
              - automation/setup
        - automation/code_linting:
            build_variant: debug
            requires:
              - automation/setup
        - automation/code_coverage:
            requires:
              - automation/unit_tests
              - automation/ui_tests
        - automation/sonar:
            requires:
              - automation/code_linting
              - automation/code_coverage